package calc;


/**
* calc/calculaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculo.idl
* jueves 18 de junio de 2015 11:50:58 AM PET
*/

public interface calculaOperations 
{
  double suma (double a, double b);
  double resta (double c, double d);
  double multi (double r, double f);
  double divi (double g, double h);
  void shutdown ();
} // interface calculaOperations
