package calc;


/**
* calc/calculaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculo.idl
* jueves 18 de junio de 2015 11:50:58 AM PET
*/

public abstract class calculaPOA extends org.omg.PortableServer.Servant
 implements calc.calculaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suma", new java.lang.Integer (0));
    _methods.put ("resta", new java.lang.Integer (1));
    _methods.put ("multi", new java.lang.Integer (2));
    _methods.put ("divi", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calc/calcula/suma
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.suma (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // calc/calcula/resta
       {
         double c = in.read_double ();
         double d = in.read_double ();
         double $result = (double)0;
         $result = this.resta (c, d);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // calc/calcula/multi
       {
         double r = in.read_double ();
         double f = in.read_double ();
         double $result = (double)0;
         $result = this.multi (r, f);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // calc/calcula/divi
       {
         double g = in.read_double ();
         double h = in.read_double ();
         double $result = (double)0;
         $result = this.divi (g, h);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // calc/calcula/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calc/calcula:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public calcula _this() 
  {
    return calculaHelper.narrow(
    super._this_object());
  }

  public calcula _this(org.omg.CORBA.ORB orb) 
  {
    return calculaHelper.narrow(
    super._this_object(orb));
  }


} // class calculaPOA
