package calc;


/**
* calc/calcula.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculo.idl
* jueves 18 de junio de 2015 11:50:58 AM PET
*/

public interface calcula extends calculaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcula
