package calc;

/**
* calc/calculaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculo.idl
* jueves 18 de junio de 2015 11:50:58 AM PET
*/

public final class calculaHolder implements org.omg.CORBA.portable.Streamable
{
  public calc.calcula value = null;

  public calculaHolder ()
  {
  }

  public calculaHolder (calc.calcula initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc.calculaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc.calculaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc.calculaHelper.type ();
  }

}
