package sumaApp;


/**
* sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* miércoles 10 de junio de 2015 08:38:20 AM PET
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
