package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* miércoles 10 de junio de 2015 08:38:20 AM PET
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
