package gradoApp;


/**
* gradoApp/convGrad.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grado.idl
* miércoles 15 de julio de 2015 09:53:55 AM PET
*/

public interface convGrad extends convGradOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface convGrad
