package gradoApp;

/**
* gradoApp/convGradHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grado.idl
* miércoles 15 de julio de 2015 09:53:55 AM PET
*/

public final class convGradHolder implements org.omg.CORBA.portable.Streamable
{
  public gradoApp.convGrad value = null;

  public convGradHolder ()
  {
  }

  public convGradHolder (gradoApp.convGrad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gradoApp.convGradHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gradoApp.convGradHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gradoApp.convGradHelper.type ();
  }

}
