package gradoApp;


/**
* gradoApp/convGradPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grado.idl
* miércoles 15 de julio de 2015 09:53:55 AM PET
*/

public abstract class convGradPOA extends org.omg.PortableServer.Servant
 implements gradoApp.convGradOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("grados", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // gradoApp/convGrad/grados
       {
         double g = in.read_double ();
         double $result = (double)0;
         $result = this.grados (g);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // gradoApp/convGrad/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:gradoApp/convGrad:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public convGrad _this() 
  {
    return convGradHelper.narrow(
    super._this_object());
  }

  public convGrad _this(org.omg.CORBA.ORB orb) 
  {
    return convGradHelper.narrow(
    super._this_object(orb));
  }


} // class convGradPOA
