package gradoApp;


/**
* gradoApp/convGradOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from grado.idl
* miércoles 15 de julio de 2015 09:53:55 AM PET
*/

public interface convGradOperations 
{
  double grados (double g);
  void shutdown ();
} // interface convGradOperations
